<?

$return = Array(

	'en'	=>	Array(
		'LOGIN' => 'Login',
		'USERNAME' => 'Username',
		'PASSWORD' => 'Password',
		'LOGIN_SUBMIT' => 'Login',
		'LOGIN_FAILED' => 'Login has failed',
		'LOGOUT' => 'Logout',
		'FORM_VALUE_INVALID' => 'This value is not valid',
		'FORM_VALUE_EMPTY' => 'This value must not be empty',
		'ALL_RIGHTS_RESERVED' => 'All rights reserved',
		'NAME' => 'Name',
		'SURNAME' => 'Surname',
		'JANUARY' => 'January',
		'FEBRUARY' => 'February',
		'MARCH' => 'March',
		'APRIL' => 'April',
		'MAY' => 'May',
		'JUNE' => 'June',
		'JULY' => 'July',
		'AUGUST' => 'August',
		'SEPTEMBER' => 'September',
		'OCTOBER' => 'October',
		'NOVEMBER' => 'November',
		'DECEMBER' => 'December',
		'DAY' => 'Day',
		'MONTH' => 'Month',
		'YEAR' => 'Year',
	),
	
	'de'	=>	Array(
		'LOGIN' => 'Anmeldung',
		'USERNAME' => 'Benutzername',
		'PASSWORD' => 'Passwort',
		'LOGIN_SUBMIT' => 'Anmelden',
		'LOGIN_FAILED' => 'Anmeldung gescheitert',
		'LOGOUT' => 'Abmelden',
		'FORM_VALUE_INVALID' => 'Dieser Wert ist ungültig',
		'FORM_VALUE_EMPTY' => 'Dieser Wert darf nicht leer sein',
		'ALL_RIGHTS_RESERVED' => 'Alle Rechte vorbehalten',
		'NAME' => 'Vorname',
		'SURNAME' => 'Nachname',
		'JANUARY' => 'Januar',
		'FEBRUARY' => 'Februar',
		'MARCH' => 'März',
		'APRIL' => 'April',
		'MAY' => 'Mai',
		'JUNE' => 'Juni',
		'JULY' => 'Juli',
		'AUGUST' => 'August',
		'SEPTEMBER' => 'September',
		'OCTOBER' => 'Oktober',
		'NOVEMBER' => 'November',
		'DECEMBER' => 'Dezember',
		'DAY' => 'Tag',
		'MONTH' => 'Monat',
		'YEAR' => 'Jahr',
	),

	'fr'	=>	Array(
		'LOGIN' => 'Login',
		'USERNAME' => 'Username',
		'PASSWORD' => 'Password',
		'LOGIN_SUBMIT' => 'Login',
		'LOGIN_FAILED' => 'Login has failed',
		'LOGOUT' => 'Logout',
		'FORM_VALUE_INVALID' => 'This value is not valid',
		'FORM_VALUE_EMPTY' => 'This value must not be empty',
		'NAME' => 'Name',
		'SURNAME' => 'Surname',

		'ALL_RIGHTS_RESERVED' => 'Tous droits réservés',
		'JANUARY' => 'Janvier',
		'FEBRUARY' => 'Février',
		'MARCH' => 'Mars',
		'APRIL' => 'Avril',
		'MAY' => 'Mai',
		'JUNE' => 'Juin',
		'JULY' => 'Juillet',
		'AUGUST' => 'Août',
		'SEPTEMBER' => 'Septembre',
		'OCTOBER' => 'Octobre',
		'NOVEMBER' => 'Novembre',
		'DECEMBER' => 'Décembre',
		'DAY' => 'Jour',
		'MONTH' => 'Mois',
		'YEAR' => 'An',
	),

);
